export const TILE_EMPTY = 0;
export const TILE_CRATERS = 1;
export const TILE_TREES = 2;
export const TILE_ROAD_2WAY_STRAIGHT = 3;
export const TILE_ROAD_2WAY_CORNER = 4;
export const TILE_ROAD_3WAY = 5;
export const TILE_ROAD_4WAY = 6;

/**
 * All Turret tile values must be larger than this value!
 */
export const MINIMUM_TURRET_TILE_VALUE = 10;

export const TILE_TURRET_BULLET_MK1 = 11
export const TILE_TURRET_BULLET_MK2 = 12
export const TILE_TURRET_BULLET_MK3 = 13
export const TILE_TURRET_ENERGY_BALL_BLUE_MK1 = 21
export const TILE_TURRET_ENERGY_BALL_BLUE_MK2 = 22
export const TILE_TURRET_ENERGY_BALL_BLUE_MK3 = 23
export const TILE_TURRET_ENERGY_BALL_ORANGE_MK1 = 31
export const TILE_TURRET_ENERGY_BALL_ORANGE_MK2 = 32
export const TILE_TURRET_ENERGY_BALL_ORANGE_MK3 = 33
export const TILE_TURRET_LASER_MK1 = 41
export const TILE_TURRET_LASER_MK2 = 42
export const TILE_TURRET_LASER_MK3 = 43
export const TILE_TURRET_ROCKET_MK1 = 51
export const TILE_TURRET_ROCKET_MK2 = 52
export const TILE_TURRET_ROCKET_MK3 = 53

//avoiding double's precision loss by using factors of 2
export const ROTATION_DIVISOR = 16;
export const ROTATION_ZERO = 0 / ROTATION_DIVISOR;
export const ROTATION_90 = 1 / ROTATION_DIVISOR;
export const ROTATION_180 = 2 / ROTATION_DIVISOR;
export const ROTATION_270 = 3 / ROTATION_DIVISOR;

export const ACTION_KEY_SELECT = "SELECT"
export const ACTION_KEY_REMOVE = "REMOVE"
export const ACTION_KEY_PLACE_TURRET_BULLET_MK1 = "PLACE_TURRET_BULLET_MK1"
export const ACTION_KEY_PLACE_TURRET_BULLET_MK2 = "PLACE_TURRET_BULLET_MK2"
export const ACTION_KEY_PLACE_TURRET_BULLET_MK3 = "PLACE_TURRET_BULLET_MK3"
export const ACTION_KEY_PLACE_TURRET_ENERGY_BALL_BLUE_MK1 = "PLACE_TURRET_ENERGY_BALL_BLUE_MK1"
export const ACTION_KEY_PLACE_TURRET_ENERGY_BALL_BLUE_MK2 = "PLACE_TURRET_ENERGY_BALL_BLUE_MK2"
export const ACTION_KEY_PLACE_TURRET_ENERGY_BALL_BLUE_MK3 = "PLACE_TURRET_ENERGY_BALL_BLUE_MK3"
export const ACTION_KEY_PLACE_TURRET_ENERGY_BALL_ORANGE_MK1 = "PLACE_TURRET_ENERGY_BALL_ORANGE_MK1"
export const ACTION_KEY_PLACE_TURRET_ENERGY_BALL_ORANGE_MK2 = "PLACE_TURRET_ENERGY_BALL_ORANGE_MK2"
export const ACTION_KEY_PLACE_TURRET_ENERGY_BALL_ORANGE_MK3 = "PLACE_TURRET_ENERGY_BALL_ORANGE_MK3"
export const ACTION_KEY_PLACE_TURRET_LASER_MK1 = "PLACE_TURRET_LASER_MK1"
export const ACTION_KEY_PLACE_TURRET_LASER_MK2 = "PLACE_TURRET_LASER_MK2"
export const ACTION_KEY_PLACE_TURRET_LASER_MK3 = "PLACE_TURRET_LASER_MK3"
export const ACTION_KEY_PLACE_TURRET_ROCKET_MK1 = "PLACE_TURRET_ROCKET_MK1"
export const ACTION_KEY_PLACE_TURRET_ROCKET_MK2 = "PLACE_TURRET_ROCKET_MK2"
export const ACTION_KEY_PLACE_TURRET_ROCKET_MK3 = "PLACE_TURRET_ROCKET_MK3"

export const ENEMY_HEALTH_BAR_OFFSET_PX = 30;
