export const TILE_EMPTY = 0;
export const TILE_CRATERS = 1;
export const TILE_TREES = 2;
export const TILE_ROAD_2WAY_STRAIGHT = 3;
export const TILE_ROAD_2WAY_CORNER = 4;
export const TILE_ROAD_3WAY = 5;
export const TILE_ROAD_4WAY = 6;

/**
 * All Turret tile values must be larger than this value!
 */
export const TURRET_TILE_VALUE_LOWER_LIMIT = 10;

export const TILE_TURRET_BULLET_MK1 = 11
export const TILE_TURRET_BULLET_MK2 = 12
export const TILE_TURRET_BULLET_MK3 = 13
export const TILE_TURRET_ENERGY_BALL_BLUE_MK1 = 21
export const TILE_TURRET_ENERGY_BALL_BLUE_MK2 = 22
export const TILE_TURRET_ENERGY_BALL_BLUE_MK3 = 23
export const TILE_TURRET_ENERGY_BALL_ORANGE_MK1 = 31
export const TILE_TURRET_ENERGY_BALL_ORANGE_MK2 = 32
export const TILE_TURRET_ENERGY_BALL_ORANGE_MK3 = 33
export const TILE_TURRET_LASER_MK1 = 41
export const TILE_TURRET_LASER_MK2 = 42
export const TILE_TURRET_LASER_MK3 = 43
export const TILE_TURRET_ROCKET_MK1 = 51
export const TILE_TURRET_ROCKET_MK2 = 52
export const TILE_TURRET_ROCKET_MK3 = 53

//avoiding double's precision loss by using factors of 2
export const ROTATION_DIVISOR = 16;
export const ROTATION_ZERO = 0 / ROTATION_DIVISOR;
export const ROTATION_90 = 1 / ROTATION_DIVISOR;
export const ROTATION_180 = 2 / ROTATION_DIVISOR;
export const ROTATION_270 = 3 / ROTATION_DIVISOR;

export const ACTION_KEY_SELECT = "SELECT"
export const ACTION_KEY_REMOVE = "REMOVE"
export const ACTION_KEY_PLACE_TURRET_BULLET_MK1 = "PLACE_TURRET_BULLET_MK1"
export const ACTION_KEY_PLACE_TURRET_BULLET_MK2 = "PLACE_TURRET_BULLET_MK2"
export const ACTION_KEY_PLACE_TURRET_BULLET_MK3 = "PLACE_TURRET_BULLET_MK3"
export const ACTION_KEY_PLACE_TURRET_ENERGY_BALL_BLUE_MK1 = "PLACE_TURRET_ENERGY_BALL_BLUE_MK1"
export const ACTION_KEY_PLACE_TURRET_ENERGY_BALL_BLUE_MK2 = "PLACE_TURRET_ENERGY_BALL_BLUE_MK2"
export const ACTION_KEY_PLACE_TURRET_ENERGY_BALL_BLUE_MK3 = "PLACE_TURRET_ENERGY_BALL_BLUE_MK3"
export const ACTION_KEY_PLACE_TURRET_ENERGY_BALL_ORANGE_MK1 = "PLACE_TURRET_ENERGY_BALL_ORANGE_MK1"
export const ACTION_KEY_PLACE_TURRET_ENERGY_BALL_ORANGE_MK2 = "PLACE_TURRET_ENERGY_BALL_ORANGE_MK2"
export const ACTION_KEY_PLACE_TURRET_ENERGY_BALL_ORANGE_MK3 = "PLACE_TURRET_ENERGY_BALL_ORANGE_MK3"
export const ACTION_KEY_PLACE_TURRET_LASER_MK1 = "PLACE_TURRET_LASER_MK1"
export const ACTION_KEY_PLACE_TURRET_LASER_MK2 = "PLACE_TURRET_LASER_MK2"
export const ACTION_KEY_PLACE_TURRET_LASER_MK3 = "PLACE_TURRET_LASER_MK3"
export const ACTION_KEY_PLACE_TURRET_ROCKET_MK1 = "PLACE_TURRET_ROCKET_MK1"
export const ACTION_KEY_PLACE_TURRET_ROCKET_MK2 = "PLACE_TURRET_ROCKET_MK2"
export const ACTION_KEY_PLACE_TURRET_ROCKET_MK3 = "PLACE_TURRET_ROCKET_MK3"

export const ENEMY_HEALTH_BAR_OFFSET_PX = 30;

export const ENEMY_Z_INDEX = 1;
export const TURRET_BASE_Z_INDEX = 4;
export const TURRET_TOP_Z_INDEX = 6;
export const TILE_SELECTOR_Z_INDEX = 8;
export const PROJECTILE_Z_INDEX = 10;
export const ENEMY_HEALTH_BAR_BOX_Z_INDEX = 11;
export const ENEMY_HEALTH_BAR_BACKGROUND_INDICATOR_Z_INDEX = 12;
export const ENEMY_HEALTH_BAR_FOREGROUND_INDICATOR_Z_INDEX = 13;
export const UI_TOP_PANEL_Z_INDEX = 100;
export const UI_SIDE_PANEL_Z_INDEX = 99;
export const UI_INFO_FIELD_BOX_Z_INDEX = 101;
export const UI_INFO_FIELD_ICON_Z_INDEX = 102;
export const UI_INFO_FIELD_TEXT_Z_INDEX = 103;
export const UI_SEPARATOR_Z_INDEX = 101;
export const UI_CLICKABLE_FIELD_BOX_Z_INDEX = 101;
export const UI_CLICKABLE_FIELD_BORDER_Z_INDEX = 102;
export const UI_CLICKABLE_FIELD_OVERLAY_Z_INDEX = 103;
export const UI_CLICKABLE_FIELD_IMAGE_Z_INDEX = 104;
export const UI_CLICKABLE_FIELD_LAYER_Z_INDEX = 110;
